[package]
name = "ripgrep-gcs"
version = "0.1.0"
authors = ["Michael Markieta <markieta.m@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
